//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnici()
        {
            this.ProfesoriPredmetis = new HashSet<ProfesoriPredmeti>();
        }
    
        public int korisnikID { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public System.DateTime datumRodjenja { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string pssw { get; set; }
        public Nullable<bool> isProfesor { get; set; }
        public Nullable<int> gradID { get; set; }
    
        public virtual Gradovi Gradovi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfesoriPredmeti> ProfesoriPredmetis { get; set; }
    }
}
