//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predmeti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Predmeti()
        {
            this.Ocjenes = new HashSet<Ocjene>();
            this.ProfesoriPredmetis = new HashSet<ProfesoriPredmeti>();
        }
    
        public int predmetID { get; set; }
        public string nazivPredmeta { get; set; }
        public string sifraPredmeta { get; set; }
        public int profesorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocjene> Ocjenes { get; set; }
        public virtual Profesori Profesori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfesoriPredmeti> ProfesoriPredmetis { get; set; }
    }
}
