//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesoriPredmeti
    {
        public int profesorPredmetID { get; set; }
        public int predmetID { get; set; }
        public int profesorID { get; set; }
    
        public virtual Predmeti Predmeti { get; set; }
        public virtual Profesori Profesori { get; set; }
    }
}
